version: "2"
run:
  tests: false
linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - misspell
    - unconvert
    - ineffassign
    - revive
    - gosec
    - gocritic
    - whitespace
    - wsl_v5
  settings:
    gocritic:
      enable-all: true
    revive:
      confidence: 0.1
      enable-all-rules: true
      rules:
        - name: cognitive-complexity
          severity: warning
          arguments:
            - 15
        - name: line-length-limit
          severity: warning
          arguments:
            - 100
        # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#var-naming
        - name: var-naming
          severity: error
          disabled: false
          # exclude: [""]
          arguments:
            - ["ID"] # AllowList
            - [""] # block list
            - - skipInitialismNameChecks: false
                upperCaseConst: false
                skipPackageNameChecks: false
                extraBadPackageNames":
                  - helpers
                  - models
                  - utils
                  - util
                  - common
                  - misc
formatters:
  enable:
    - goimports
    - gofmt
